# Generated by Django 4.1 on 2022-09-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_sampleitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleitem',
            old_name='sampleroom',
            new_name='roomname',
        ),
    ]
