# Generated by Django 4.1 on 2022-09-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_rename_sampleroom_sampleitem_roomname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleitem',
            old_name='roomname',
            new_name='sampleroom',
        ),
    ]
