# Generated by Django 4.1 on 2022-09-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_rename_roomname_sampleitem_sampleroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleitem',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
