# Generated by Django 4.1 on 2022-09-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_remove_sampleitem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
