# Generated by Django 4.1 on 2022-09-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_sampleitem_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleitem',
            name='Comment',
        ),
    ]
