# Generated by Django 4.1 on 2022-09-12 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0014_sampleroom_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleitem',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='item_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
