# Generated by Django 4.1 on 2022-09-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_sampleitem_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Revenue', models.IntegerField()),
            ],
        ),
    ]
