# Generated by Django 4.1.1 on 2022-09-22 06:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0016_producta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate_a_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cate_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate_b_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sampleitem',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('size', models.IntegerField(default=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('qty', models.IntegerField(default=1)),
                ('get_date', models.DateField(default=datetime.date.today)),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('delete_flag', models.BooleanField(default=False, verbose_name='')),
                ('delete_date', models.DateTimeField(auto_now_add=True)),
                ('cate_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.cate_a')),
                ('cate_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.cate_b')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_owner', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.room')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
