# Generated by Django 4.1 on 2022-09-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_cate_a_cate_b_alter_sampleitem_options_room_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate_a',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cate_b',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
