# Generated by Django 4.1 on 2022-09-23 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_alter_cate_a_name_alter_cate_b_name_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cate_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.cate_a'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cate_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.cate_b'),
        ),
        migrations.AlterField(
            model_name='item',
            name='delete_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
