# Generated by Django 4.1.1 on 2022-09-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_alter_item_cate_a_alter_item_cate_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cate_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.cate_a'),
        ),
    ]
