# Generated by Django 4.1.1 on 2022-09-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0021_alter_item_cate_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
