# Generated by Django 4.1.1 on 2022-09-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0022_alter_item_delete_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delete_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
