# Generated by Django 4.1.1 on 2022-09-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0023_alter_item_delete_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cate_a',
            old_name='name',
            new_name='namea',
        ),
        migrations.RenameField(
            model_name='cate_b',
            old_name='name',
            new_name='nameb',
        ),
    ]
